### ISSUE TITLE
Selecting a custom asset should allow displaying a custom asset view

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-plugin-beta#103]
This would be provided by the plugin providing the asset.

It would be where our current "deposit/send/history" view is now, but could be custom to that particular selected asset.

Currently custom assets can provide a link URL, we could simply open that URL in an iframe.

**Comment by rekmarks** [comment]
Custom assets is a highly complex feature currently at the design stage and will be tracked elsewhere.
