### ISSUE TITLE
Design/finalize custom asset API

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-plugin-beta#111]
The current plugin beta has a [custom asset management api](https://github.com/MetaMask/metamask-snaps-beta/wiki/Plugin-API#custom-asset-management), which allows plugins to list their assets in the main token list.

I say asset instead of tokens, because these don't need to be tokens, they can be anything a plugin chooses to render. So far we've seen a few of these built!:
- Layer 2 assets
- Other blockchain tokens
- Collectibles
- Incoming messages
- Subscriptions
- Allowances

The current implementation allows just a few things to be provided here:
- an asset "symbol" (short description)
- an asset icon
- a longer name
- a numeric value/quantity
- a link to visit on click. Clicking may result in showing a custom view in-page: https://github.com/MetaMask/metamask-snaps-beta/issues/103

There are also some security critical features of these.
- It should be easy to distinguish the (plugin?) source of a given asset (label the provenance).

**Comment by rekmarks** [comment]
Complex feature that will be tracked elsewhere.
