### ISSUE TITLE
Add "Reload Plugins" button

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-plugin-beta#117]
We currently have two plugin-beta-specific buttons we're throwing at the bottom of the MetaMask UI:
- Clear plugin state
- Reset permissions

I propose we add another:
- Reload plugins

This would be intended to aid in development, when the plugin-adding flow is not the subject of the testing, but instead the plugin behavior is, but the plugin code has been updated at its source, and so the dev just wants to reload their plugin.

#### Super-Stretch Goal

Might even be cool if a site could request "permission to trigger plugin updating", because in development, this could be used to create a live-reload flow where the plugin is rebuilt on file change, if recognized by the app.

**Comment by rekmarks** [comment]
No longer relevant.
