### ISSUE TITLE
Implement security audit feedback

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-plugin-beta#118]
Sharing openly since none of this is in production yet, a few action items we'd like to complete before we bring any to production: https://docs.google.com/document/d/1VIZ77C5OEoGbTNFUW8nTL7oguFfNNevoy6gcDCiCKkI/edit#

## Things to do before MVP
- [ ] Disable SES error stack in production environment builds.
- [ ] Remove `submitPassword` and `getState` from restricted methods, at least.
- [ ] Ensure state isolation of plugins (perhaps at the storage layer, or via tests)
- [ ] Freeze process.env at boot
- [ ] In assets.js, use truthiness checks not `foo in bar` when sensible.
- [ ] Deep audit whether under any condition a plugin can send a message with an impersonated `origin` string. At least isolate `getAccounts` from `selectedAddress` method.

## Things to do before prod:
- [ ] Ensure plugins receive their own storage mechanisms, so they cannot interfere at all with the main app. #88, MetaMask/metamask-extension#7311

**Comment by rekmarks** [comment]
No longer relevant.
