### ISSUE TITLE
Build installed with yarn start, doesn't work

### ISSUE THREAD

**Issue by Solexplorer** [MetaMask/metamask-plugin-beta#120]
**Describe the bug**
I have followed the instructions in [here](https://github.com/MetaMask/metamask-snaps-beta/wiki/Getting-Started) and have successfully installed packages with `yarn install` and did run `yarn start`.
When I try to load unpacked extension it throws me this error: 
![image](https://user-images.githubusercontent.com/50027175/69571758-08dd9480-0fc3-11ea-9875-a44126464216.png)

Is it working on Windows 🤔 ?
**To Reproduce**
Just load the unpacked extension after successfully running `yarn install` and `yarn start`

**Expected behavior**
A clear description of what you expected to happen.
To load the extension

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome Version 78.0.3904.108 (Official Build) (64-bit)
 - MetaMask Version 7.6.1

**Additional context**

**Comment by Solexplorer** [comment]
Btw, how do I join team metamask_plugins that @danfinlay said in his [medium post](https://medium.com/metamask/introducing-the-next-evolution-of-the-web3-wallet-4abdf801a4ee)?

**Comment by rekmarks** [comment]
>Is it working on Windows 🤔 ?

@solexplorer, are you on Windows? We have not tested or developed for Windows, and I'd expect it to not work at this point. We hope to add Windows support for plugin development in the not-too-distant future.

Regarding communication channels, we recommend our Telegram group, here: https://t.me/mmsnaps

**Comment by lazaridiscom** [comment]
Just tried, this works on my side.

Though some errors are listed after i install it in chrome, i can create a wallet and mm appears normal.

The errors are (chrome://extensions listing, Metamask's section DETAILS, REMOVE, **ERRORS** )

```
Invalid asm.js: Unexpected token
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit
MetaMask: You are using the experimental plugin version of MetaMask.
```

seems non-critical errors, as mm starts normally.

## Recreation

```sh
git clone https://github.com/MetaMask/metamask-snaps-beta.git mm-snaps
cd mm-snaps
yarn install
yarn dist
```

then add `mm-snaps/dist/chrome` as an unpacked extension.

## System

```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362

Google Chrome is up to date
Version 78.0.3904.108 (Official Build) (64-bit)
```

**Comment by Solexplorer** [comment]
Wait, I cloned metamask-plugin-beta as outlined by the wiki not metamask-snaps-beta. What is the correct repo ?

**Comment by rekmarks** [comment]
The correct repo is `metamask-snaps-beta`, although `metamask-plugin-beta` should point to that.

**Comment by lazaridiscom** [comment]
Maybe update the docs to avoid confusion.

**Comment by Solexplorer** [comment]
Ok it's working for me on another PC by installing snaps-beta. Thanks for the help!
