### ISSUE TITLE
Ensure proper Windows support

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-plugin-beta#121]
The status of our Windows support is unclear. `snaps-cli` and path resolution when loading plugin manifests may not work.

Related: #120

**Comment by lazaridiscom** [comment]
As reported within https://github.com/MetaMask/metamask-snaps-beta/issues/120#issuecomment-558350329 a quick test worked on my win10 native side.

You should possibly raise the priority here, nix-win-mac trio should be a "must" requirement, even during development.

**Comment by rekmarks** [comment]
`@metamask/snaps-cli` supports Windows at the time of writing.
