### ISSUE TITLE
Can't use address with checksum as a custom account

### ISSUE THREAD

**Issue by xuhcc** [MetaMask/metamask-plugin-beta#124]
**Describe the bug**

The `eth_accounts` call returns empty array when I register checksummed address as a custom account. It works properly if provided address is in lower case.

**To Reproduce**

1. Add custom account by calling `wallet_manageIdentities` method with these params:
`['add', {address: '0xBB9bc244D798123fDe783fCc1C72d3Bb8C189413'}]`.
2. Switch to newly added account.
3. Grant permission by sending `wallet_requestPermissions` call.
4. Send `eth_accounts` call. 
5. `eth_accounts` call returns empty array.

**Expected behavior**

`eth_accounts` should return currently selected custom account.

**Browser details (please complete the following information):**

 - OS: Arch Linux
 - Browser: Chromium
 - MetaMask Version: c4dd46e4e038b8a9b25e10000d2cf3a081f0dcea

**Comment by rekmarks** [comment]
No longer relevant, as whatever custom accounts API we end up shipping is unlikely to work the way it did on this beta. Ref: https://docs.metamask.io/guide/snaps.html
