### ISSUE TITLE
Extension fails to load

### ISSUE THREAD

**Issue by xuhcc** [MetaMask/metamask-plugin-beta#127]
**Describe the bug**

Extension fails to load: `Cannot read property 'methodNotFound' `

**To Reproduce**
1. Build extension from develop branch.
2. Load unpacked extension in Chrome.
3. Click on extension icon.
4. Popup window is blank.

**Expected behavior**

Extension should show the welcome page.

**Browser details (please complete the following information):**
 - OS: Arch Linux
 - Browser: Chromium
 - MetaMask Version: 45361945e915d29940963befb5bbd373655b51f4

**Additional context**

The bug was introduced with commit 45361945e915d29940963befb5bbd373655b51f4.

130a6d2dad321df30842482b62daafc64f966c79 is working fine.

**Comment by rekmarks** [comment]
Can you please try the following two potential solutions?

1. Run `yarn install --force` then `yarn start`, and see if the error disappears
2. Go to `chrome://extensions`, remove the unpacked extension, then load the unpacked extension
  a. Make sure that `yarn start` is running the the extension root folder, and that the `dev:copy` task has finished before attempting to load the unpacked extension from `metamask-snaps-beta/dist/chrome`

If neither of those work, can you please post the complete error, with the stack?

**Comment by xuhcc** [comment]
Yes, here's the full stacktrace:
```
background.js:357736 Uncaught TypeError: Cannot read property 'methodNotFound' of undefined
    at Object.metamask-snaps-beta/node_modules/rpc-cap/dist/src/errors.js.eth-json-rpc-errors (background.js:357736)
    at o (background.js:1)
    at background.js:1
    at Object.metamask-snaps-beta/node_modules/rpc-cap/dist/src/caveats.js../errors (background.js:357675)
    at o (background.js:1)
    at background.js:1
    at Object.metamask-snaps-beta/node_modules/rpc-cap/dist/index.js../src/caveats (background.js:357246)
    at o (background.js:1)
    at background.js:1
    at Object.metamask-snaps-beta/app/scripts/controllers/permissions/permissions.js../loggerMiddleware (background.js:2633)
```

By the way, I usually use `yarn dist` to rebuild extension. Is there any significant difference between it and `yarn start`?

**Comment by rekmarks** [comment]
Woah, our bad. We'd published a broken version of `rpc-cap`. That package is updated and this problem should never occur again. Thanks for bringing it to our attention!
