### ISSUE TITLE
Add low-resolution wrappers for timing functions

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-plugin-beta#135]
We should not provide high-resolution timers to plugins, but some plugins do require a sense of time. For those, we should provide a low-resolution access to time, and probably make it a permission, too.

Added timers for beta purposes (ethers uses timers to monitor transaction completion) in https://github.com/MetaMask/metamask-snaps-beta/pull/134

**Comment by kumavis** [comment]
i assume this is related to timing attacks, including spectre style vulns
