### ISSUE TITLE
Changing a running plugin's permissions should always affect its API

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-plugin-beta#139]
Currently, a plugin's API is generated at its initialization, and is effectively immutable. If we remove permissions from a running plugin, it will only be restricted from accessing those permissions if they correspond to RPC methods. Any methods it can call directly using e.g. global APIs, MetaMask APIs, or `capnode` will still work.

We should be able to dynamically restrict or expand a plugin's API.

Related #38

**Comment by danfinlay** [comment]
Related to (maybe duplicate of) #38.

We currently have no permissions system for JS APIs.

Was recently discussing the ideal schema with @kumavis. We were thinking of a few different approaches.

- Use a similar schema to [sesify-tofu](https://github.com/LavaMoat/sesify-tofu) (which itself needs expanding).
- Use a schema based on rpc-cap, but just use it to generate "disruptor functions", in the [SJE membrane](https://github.com/caridy/secure-javascript-environment) sense of the term (basically a caveat in the rpc-cap lexicon).

We could also do both: If we use SJE as a membrane layer for permissioning JS APIs, we could generate those disruptor/caveat functions in any of a variety of ways, including a tofu-style config, an rpc-cap style schema, ocap-ld, or whatever else we decide to do.

Ultimately, this all comes down to writing a membrane around an native API (maybe start with fetch), and see how well we can constrain it based on a permissions table (like rpc-cap).

**Comment by rekmarks** [comment]
No longer relevant.
