### ISSUE TITLE
Js Alert when I click on the send Hello Button

### ISSUE THREAD

**Issue by traumaxp** [MetaMask/metamask-plugin-beta#142]
I reproduced the steps to test an example but I have this error in a JS Alert when I click on the sendHello Btn

'Problem happened: The MetaMask Web3 object does not support synchronous methods like wallet_plugin_http://localhost:8081/package.json without a callback parameter.'

Thanks

**Comment by rekmarks** [comment]
Hi @GuillaumeFERNANDESXP, it sounds like you have the normal version of the extension loaded in the browser. Have you followed the steps in the Wiki?

https://github.com/MetaMask/metamask-snaps-beta/wiki/Getting-Started

**Comment by traumaxp** [comment]
Hi @rekmarks, it works very well, thanks !
