### ISSUE TITLE
wallet.addAddressAudit doesn't use correct "auditor"

### ISSUE THREAD

**Issue by craze3** [MetaMask/metamask-plugin-beta#143]
When I try to use the `wallet.addAddressAudit` API, it only **sometimes** displays the auditor name I supplied in my `index.js`. The other times it still displays "Awesome Audits". Is this some sort of placeholder code that was never removed from the dev branch?

Every time I change my `index.js`, I re-run `mm-snap build` followed by `mm-snap serve`. Then, I delete all plugins from my MetaMask and reinstall fresh from the newly served page. When I add new things to the codebase (such as console.log()'s), I am able to see them appearing/active, so I know my new code is being loaded. I have even tried re-loading MetaMask from `chrome://extensions/` and that doesn't seem to affect it either. My MetaMask build is the `develop` branch of the `metamask-snaps-beta` repo (last updated 10 days ago), and I was able to build it just fine (using the correct Node version thanks to NVM).

**To Reproduce**
I'm just using the same code from the examples directory:
```
function mockAuditApi (address) {
  return new Promise(resolve => {
    const lastDigit = address.slice(address.length - 1)
    resolve(Boolean(lastDigit.toLowerCase().match(/[a-f]/)))
  })
}

wallet.onMetaMaskEvent('newUnapprovedTx', async (txMeta) => {
  const { txParams } = txMeta
  const addressIsUntrustworthy = await mockAuditApi(txParams.to)
  wallet.addAddressAudit({
    address: txParams.to,
    auditor: 'BlockSpy',
    status: addressIsUntrustworthy ? 'warning' : 'approval',
    message: addressIsUntrustworthy
      ? 'The recipient of this transaction is untrustworthy'
      : 'The recipient of this transaction is trustworthy',
  })
})
```

It should be displaying my auditor name instead of the default one....
Can anyone help ?

**Comment by rekmarks** [comment]
Hi, thank you for bringing this to our attention. I believe that the behavior you describe is due to the address audit state never being cleared. In addition, we may not be managing state for multiple different auditors correctly (or at all).

The address auditing functionality is still experimental, and we may not fully solve this problem at this time. See #144 for more details.

**Comment by craze3** [comment]
Thanks for the prompt response @rekmarks ! I pulled the latest changes (#144), did a rebuild, and reloaded the extension, but I'm still having the same problem.

If there's any way I can help, please let me know. Also curious if there is a community slack/chat i can join to chat with other MetaMask devs. Gitter appears dead...

**Comment by rekmarks** [comment]
Hm. Did you clear permissions state using the "Delete All Permissions" button in the extension UI?

Also, for developer community, the most active channel right now is: https://t.me/mmsnaps

**Comment by craze3** [comment]
That fixed it! It's working, thanks so much guys. I am joining the telegram and closing this issue now. 🙏🏼
