### ISSUE TITLE
Successful transaction reported as failed by custom account

### ISSUE THREAD

**Issue by xuhcc** [MetaMask/metamask-plugin-beta#152]
**Describe the bug**

Here's the code:

```javascript
wallet.registerAccountMessageHandler(async (originString, requestObject) => {
    switch (requestObject.method) {
        case 'eth_signTransaction':
            return true
        default:
            throw Error('Method not supported.')
    }
})
```

After returning from this account message handler, metamask throws an error:

```
background.js:1 Error in RPC response:
 Objectid: 3259821713
jsonrpc: "2.0"
error: code: -32603
message: "Error: [ethjs-rpc] rpc error with payload {"id":8015515134679,"jsonrpc":"2.0","params":["0x..."],"method":"eth_sendRawTransaction"} [object Object]"
```

**Browser details (please complete the following information):**
 - OS: Arch Linux
 - Browser: Chromium
 - MetaMask Version: develop / 220784cafd2e22bed083e385ef247810660966db

**Comment by rekmarks** [comment]
We will ship custom accounts using a completely different API at some point in the future. This repo will soon be archived, and I will close this issue for now.

Ref: https://docs.metamask.io/guide/snaps.html
