### ISSUE TITLE
Long snap urls breaks permission screen

### ISSUE THREAD

**Issue by mpetrunic** [MetaMask/metamask-plugin-beta#158]
**Describe the bug**
If snap is using long urls as origin (ipfs in this case) it breaks UI of confirmation screen

**To Reproduce**
1. Install snap using origin: "https://ipfs.infura.io/ipfs/QmXTu32iPygL2LTvidc4YkpHCoTarDZS2Ks6fa7LVwPVD3"
2. Connect

**Expected behavior**
A clear description of what you expected to happen.
Popup should resize and/or wrap long data.

**Screenshots**
![image](https://user-images.githubusercontent.com/8836210/81784232-d6860c00-94fc-11ea-8a8c-8a5b52fddf47.png)

**Browser details (please complete the following information):**
 - OS: Ubuntu
 - Browser [e.g. chrome, safari]: Chromium
 - MetaMask Version [e.g. 5.0.2] develop build

**Additional context**

**Comment by rekmarks** [comment]
This should hopefully not be the case in the current system, but if it is, an issue should be created on the metamask-extension repo.
