### ISSUE TITLE
Remove as many global endowments as possible

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-plugin-beta#161]
In particular `setTimeout` and `setInterval` are themselves evaluators, and so can lead to sandbox escapes, and so we should not expose them without attenuating them into a new form.

We could also provide proxies of those functions that:
- [ ] Require the first arg is a function.
- [ ] Increase the minimum granularity of the timing

**Comment by rekmarks** [comment]
No longer relevant.
