### ISSUE TITLE
Support for other cryptocurrencies/cryptographies

### ISSUE THREAD

**Issue by filips123** [MetaMask/metamask-plugin-beta#60]
**What problem are you trying to solve?**

MetaMask only supports Ethereum-compatible networks. However, there are a lot of other blockchains and cryptographies which aren't currently supported in MetaMask. To make MetaMask true Meta-Wallet, more cryptocurrencies and cryptographies should be supported.

(I don't know if this is a correct repository for this request, but you can move it if needed.)

**Describe the solution you'd like**

There should be "official" support for most popular blockchains (Bitcoin, Litecoin, EOS...) and also the ability to integrate custom blockchain and cryptography. Although Bitcoin (and many other cryptocurrencies) doesn't have smart contract features, it can still be used to send normal transactions and cryptographic operations (signing). This would really expend the possibilities of MetaMask and web dapps.

**Comment by danfinlay** [comment]
Both cryptocurrencies and cryptographies can be described as plugins. We may build official modules for them soon, but first we are shipping the framework, so we do not need to be the only team securely contributing them.

**Comment by filips123** [comment]
@danfinlay When it is expected for plugins framework and cryptography plugins to be added?

**Comment by danfinlay** [comment]
The plugin system is likely to roll out over the course of the next year. New cryptography plugins should be available immediately, as we already have working examples of two types, bls signatures and zk-starks.

[bls signer example](https://github.com/MetaMask/mm-plugin/tree/master/examples/bls-signer)
