### ISSUE TITLE
Build for Firefox

### ISSUE THREAD

**Issue by filips123** [MetaMask/metamask-plugin-beta#61]
Can you also build this beta version for Firefox?

**Comment by danfinlay** [comment]
Added, but it may not work, we haven't been testing on it yet: https://github.com/MetaMask/metamask-plugin-beta/releases/tag/devcon

**Comment by danfinlay** [comment]
Feel free to open a new issue if it is not working ;)

**Comment by filips123** [comment]
@danfinlay Firefox build is again missing from newsest releases. Can you add it back?
