### ISSUE TITLE
Add method for plugins to export app keys

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-plugin-beta#69]
I'm not sure whether we should trust plugins to generate their own app keys (probably?), but since some account types aren't even key pairs, we might want to also provide some default key generation.

Relevant code [here](https://github.com/MetaMask/metamask-plugin-beta/blob/5cc1cf32fbef9bad5fc2ed0c6297eb8721991490/app/scripts/controllers/accounts.js#L159).

To allow total interacting between plugins even with custom accounts, this is a requirement, so it should be at least dismissed with good reason before production, so marking as prod-blocker.

**Comment by rekmarks** [comment]
Part of some future app key epic that we will track elsewhere through other means.
