### ISSUE TITLE
Localize permissions descriptions

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-plugin-beta#71]
Not only should we have translations on permissions descriptions, it is probably a good time to further enhance the resilience of our translation merging process, because permissions descriptions are so critical to the security of the system.

One idea is to have a bot that runs proposed translation changes through multiple translation services and presents them in a comment for easier human review, without knowing the source language. Open to other improvement ideas too.

Marking as prod-blocker for now, but could unblock with a reasonable alternative path to securing these translations. Also we may want this done for the `LoginPerSite` branch anyways (which is earlier than plugin system for production).

**Comment by rekmarks** [comment]
We've done this on the production extension for some time.
