### ISSUE TITLE
Reduce permissions history bloat

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-plugin-beta#74]
I think I found part of why my plugin extension is getting slow: We're recording every permissions act ever made, and including it in the state provided with each UI update. This is unreasonable.

We need to either cut this history short, or store it in a separate portion of state that is not constantly included with the UI.

Related to https://github.com/MetaMask/metamask-extension/issues/7311

**Comment by rekmarks** [comment]
Some notes on this:
- There are technically two permissions logs in state, the history and the activity logs. They're managed by the same middleware.
- The history log keeps track of which domains have had which permissions. It doesn’t have a limit, but it grows slowly, and I can’t imagine it’s causing our performance issues.
- The activity log records, as mentioned, everything, but it’s capped at 100 entries. That should not amount to many kilobytes of memory, but I haven’t benchmarked it.
- With respect to logging, the other thing impacting performance could be the permissions logger middleware itself. It shouldn’t cause slowdowns on boot, however, as we have seen on some machines.
- To see if logging makes a difference, we could just comment out the lines where the logger middleware is pushed to the permissions middleware stack in the permissions controller.

**Comment by rekmarks** [comment]
Not specific to snaps, tracked elsewhere.
