### ISSUE TITLE
Publish EIP on appKey method we are using

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-plugin-beta#78]
We are using a variant of EIP 1775, and we should document it, either by updating that EIP, or by submitting a new one.

**Comment by Bunjin** [comment]
I can help updating EIP 1775 if required.

**Comment by rekmarks** [comment]
Resources
- Algorithm described in the Ethereum Magicians [app keys EIP thread](https://ethereum-magicians.org/t/eip-erc-app-keys-application-specific-wallet-accounts/2742/37)
 - Algorithm implemented in [eth-simple-keyring](https://github.com/MetaMask/eth-simple-keyring/blob/6d12bd9d73adcccbe0b0c7e32a99d279085e2934/index.js#L139-L152)

**Comment by Bunjin** [comment]
I updated EIP1775
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1775.md

Concerning BIP44 compliant HD keys, they are outside of the scope of EIP1775, see #104.
