### ISSUE TITLE
Add checksum to "bundle" field of plugin package.json

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-plugin-beta#93]
Along with adding more decentralized distribution channels, having the checksum encoded would ensure we could load plugins with integrity.

**Comment by rekmarks** [comment]
This has been done as of the `v0.1` snaps manifest: https://github.com/MetaMask/specifications/blob/d4a5bf5d6990bb5b02a98bd3f95a24ffb28c701c/snaps/publishing.md
